var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                              w     x      xx    xx    xxxx                     ",
   "                                                                                ",
   "                                                         xxxx                   ",
   "                            xxxxx                                               ",
   "                                             w                              xxxx",
   "  xx                                                                         xxx",
   "  x                     o                                                xx  xxx",
   "  x            oo                          xxxxxx                 xx  =   xx xxx",
   "  x  y       xxxxx      o       o                               x   e        xxx",
   "  x  @     e xxxxx e  x                                       xxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxx   xxxxx    o        o        xx       xxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxx   xxxxx   xxx               xx    x   xxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxx!!!xxxxx!!!xxx  xx     xx    xx!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxx!!!xxxxx!!!xxx              =xx!!!!!!!!xxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      e        xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                "],
  ["      x!!x                            x!!x                        xxxxxxx                                    x!x  ",
   "      x!!xx                           x!!x                     xxxx     xxxx                                 x!x  ",
   "      x!!!!xxxxxxxxxxxxxxxxxxx        x!!xxxxxxxxxx           xx           xx                 xxxxxxxxxxxxxxxx!x  ",
   "      x!!xx!!!!!!!!!!!!!!!!!!!x       xx!!!!!!!!!!xx         xx             xx                xxxxxxxxxxxxxxxx!x  ",
   "       x!x x!xxxxxxx!xxxxxxx!!x        xxxxxxxxxx!!x         x                               =xxxxxxxxxxxxxxxx!x  ",
   "       xvx  xvx    xvx     xvx                   x!x         x     w   o                      xxxxxxxxxxxxxxxx!x  ",
   "                                                 x!x         x                               =xxxxxxxxxxxxxxx!!x  ",
   "                                                 xvx         x     x   x                       =!!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xxx           xxxxxxxxxxxxxxxxxxxxx   ",
   "                                               x              xx!!!!!!!!!!!xxxxx         v   x                    ",
   "                                               x               xxxx!!!!!xxxxxxxxx            x                    ",
   "                                               x                  xxxxxxxxxxxxxxxxxx         xxx                  ",
   "                                               x     xx                          x x         x x                  ",
   "                                               x     x                             x         x                    ",
   "                                              oxo    x                             xx        x                    ",
   "                                             xxxx    x                         o   x         x                    ",
   "                                              !x     x      o  o     x   x         x        xx                    ",
   "               xx   xx        xxx   xxx       =x     x   x    e  x   x   x        =x         x                    ",
   "              xx     xx         x   x         !x    ox   xxxxxxxxx   x   x!!!xxxxxxxxx       x                    ",
   "     y       xx   x   xx        x o x       xxxx    xx               x   x!!!x             xxx                    ",
   "     @      =x!!!!!!!!!x        x   x          x     x               x   x!!!x               x                    ",
   "    xxx      x!!!!!!!!!xx       x   x         =x     x               x   xxxxx   xxxxxx      x                    ",
   "    xxx      x!!!!!!!!!x       xx o xx!!!!x!!!!xo    x |           | x     o     x!x    |    x                    ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!!!!!!x     e     x!x!!!!!!!!!x                    ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!xxxxxxxxxxxxxxxxxx!xx!!!!!!!xx                    ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!x    o                 xx!!!!!!xx!!!xxxxxxxxxxxxxxx!!!!xx!!!!!xx                     ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!x        x       e    xx!!!!!!xx!!!!!xxxxxxxxxxxxxx!!!!!xxxxxxx                      ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx!!!!!!!!xxxxxxxxxxxx!!!!!!!!!!!                       ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!xxxxxxxxxx!!!!!!!!!!!                       ",
   "!!!!xxx!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx!!!!!!!!!!!!!!xxxxxxxx                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        x                                         x                            ",
   "                                        x                                         x                            ",
   "                                        x                                         x                            ",
   "                                        x                                         x                            ",
   "                                       xxxx                                       x                           ",
   "                                       xxxx                xxx         x   xxx    x                           ",
   "                                       xxxx                !x!         x          x                           ",
   "                                     xxxxxx                !x!       xxx          x                           ",
   "                                      xxxxx              xxxx   oooo   x       xxxx                           ",
   "                                      xxxxx                 x          x       x!!x                           ",
   "                                      xxxxx                 xxxxxxxxxxxx       xxxx                           ",
   "                                     xxxxxx           x     exv     v          x                              ",
   "                                      xxxxxxxxxxxxx   xxxxxxxx             xxxxx                              ",
   "                                      xxxxx           x                    x!!!x                              ",
   "                                      xxxxx           x                    xxxxx                              ",
   "                                     xxxxxx           x                    x                                  ",
   "                                      xxxxx        xxxx            xxxxxxxxx                                  ",
   "                                      xxxxx           x           x!!!xxxxxx                                  ",
   "                                      xxxxx           x     w      xxx       xxx                              ",
   "                                     xxxxxx           x              x      x!!!x                             ",
   "                                      xxxxxxxx        x     x        x       xxv        xxx                   ",
   "                                      xxxxx           x              x                 x!!!x                  ",
   "                             xxxxxxxxxxxxxxx     o o  x!!!!!!!!!!!!!!x                  xvx                   ",
   "                             xxxxxxxxxxxxxxx          x!!!!!!!!!!!!!!x                                        ",
   "                             xxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx     x     xxx                                                                 ",
   "  xxx                         x    x!x    xxxx                                                           xxx  ",
   "  x x                         x    x!x    xxxx=             x=          o   ox                           x x  ",
   "  x                           x     v   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                             x  ",
   "  x                           x           x                              x!!!x                             x  ",
   "  x                           xx          x                              x x xx                            x  ",
   "  x                                       x                                         o                      x  ",
   "  x                                o o                                             xxx                     x  ",
   "  x                           xx                                                  x!!!xx        o          x  ",
   "  x               oxxxo       x    xxx                                  xxx        xxx         xxxx        x  ",
   "  x      y         xxx        xxxxxxxxxxxxx  x oo x  |  x oo x  |  x oo x x                    xxxx        x  ",
   "  x      @         =x       e x!!!!!!!!!!!x!!x    x!!!!!x    x!!!!!x    x x  e                 =xe        ex  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxxxx!!xxxxxxxxx!!xxxxxxxxx!!xx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "              xx      xx    xxxx    xx    xx      xx                xx  xxxxxx      xxx        xx             ",
   "               xx    xx    xx  xx   xx    xx      xx                xx    xx       xx xx       xx             ",
   "                xx  xx    xx    xx  xx    xx       xx              xx     xx       xx  xx      xx             ",
   "                 xxxx     xx    xx  xx    xx       xx     xxxx     xx     xx      xx    xx    xx              ",
   "                  xx      xx    xx  xx    xx        xx   xx  xx   xx      xx      xx     xx   xx              ",
   "                  xx      xx    xx  xx    xx        xx   xx  xx   xx      xx     xx       xx xx               ",
   "                  xx       xx  xx    xx  xx          xx xx    xx xx       xx     xx        xxxx               ",
   "                  xx        xxxx      xxxx            xxx      xxx      xxxxxx  xx          xx                ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  @                                                                                                           ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                                    ",
   "  x         x   x       x   x       x   x                                                                     ",
   "  x        xxxxx   o   xxxxx   o   xxxxx                                                                      ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
